---
title: "HW6"
author: "jgn2108"
date: "`r Sys.Date()`"
output: github_document
---

## Set up
```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(skimr)
library(dplyr)
library(broom)
library(purrr)
library(broom)
library(ggplot2)
library(tidyr)
library(stringr)
```

## Problem 1

Loading data: Washington Post homicide data
```{r}
url <- "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

# Read the CSV file into a data frame
homicide_data <- read_csv(url)

# View the first few rows of the data
head(homicide_data)
```
Data cleaning (using skimr)
```{r}
# Use the skim() function directly from skimr without loading the whole package
skim_summary <- skimr::skim(homicide_data)
print(skim_summary)
```
Reformat reported_date
```{r}
# Convert numeric date to Date object
homicide_data$reported_date <- as.Date(as.character(homicide_data$reported_date), format = "%Y%m%d")

# Format the date as MM/DD/YYYY
homicide_data$reported_date <- format(homicide_data$reported_date, "%m/%d/%Y")

```

```{r}
# Create city_state variable
homicide_data <- mutate(homicide_data, city_state = paste(city, state, sep = ", "))
```



Convert tibble into a standard df
```{r}
homicide_data_df <- as.data.frame(homicide_data)
str(homicide_data_df)
```
Create a new variable: city_state
```{r}
# Create city_state variable
homicide_data <- mutate(homicide_data, city_state = paste(city, state, sep = ", "))

# Summarize data
summary_data <- homicide_data %>%
  group_by(city_state) %>%
  summarize(
    total_homicides = n(),
    unsolved_homicides = sum(disposition %in% c("Closed without arrest", "Open/No arrest"))
  )

print(summary_data)
```

Create a new variable: city_state
```{r}
# Create city_state variable
homicide_data<- mutate(homicide_data, city_state = paste(city, state, sep = ", "))

# Summarize data
summary_data <- homicide_data %>%
  group_by(city_state) %>%
  summarize(
    total_homicides = n(),
    unsolved_homicides = sum(disposition %in% c("Closed without arrest", "Open/No arrest"))
  )

print(summary_data)
```







Create a new variable:
```{r}

```

